### ISSUE TITLE
store默认是全局的？

### ISSUE THREAD

**Issue by gongyucheng** [80percent/wechat-weapp-mobx#11]
导出
module.exports = {
   default: new orderStore
}
但是每次进入小程序页面的时候，这个store里面的属性都不是初始化的属性

**Comment by windy** [comment]
你这样写是单例的, 当然全局生效. 如果想用在每次初始化, 可以建一个 models 目录, 放业务的对象:

https://mobx.js.org/best/store.html

**Comment by gongyucheng** [comment]
@windy  但是 class 里使用extendObservable 报错啊？

**Comment by windy** [comment]
引入 mobx 组件了吗? 见 README.md 的例子.

**Comment by gongyucheng** [comment]
var extendObservable = require('../libs/mobx').extendObservable
export class Store {
    extendObservable(this, {
      hotCity: [],
      allCity: [],
      get historyCity() {
        return wx.getStorageSync('city') || []
      }
  })
}
代码大概是这个样子的，如果是demo里用函数就没问题，比如下面这个就不会有问题
var Store = function () {
  extendObservable(this, {})
}
