### ISSUE TITLE
请问在小程序的JS文件里如何读取store的值？

### ISSUE THREAD

**Issue by laoyao789** [80percent/wechat-weapp-mobx#13]
请问在小程序的JS文件里如何读取store的值？

在wxml里可以正常读取，在JS中， 目前在store中定义的字符串变量是可以读出来的，但是对象就读取不出来，对象读取出来是一个$mobx对象

**Comment by windy** [comment]
一般不会直接用到对象，你拿到的其实是 mobx 的代理对象，可以直接调它的内部方法直到拿到最终内容。

如果你确实需要用到对象，可以调用库里导出的 toJS 接口进行转化为原生 JS 对象。

**Comment by laoyao789** [comment]
下面是Store.js的代码，game的属性里有一个时间（startTime）,我需要在js里取出来这个时间，然后做倒计时的效果，目前我对mobx并不熟悉，所以不知道怎么拿到这个属性值，$mobx 对象具体怎么取值 ？建议把这个例子写到readme里，毕竟好多像我这样拿来就用的新手

store.js

var mobx = require('../libs/mobx');
var extendObservable = require('../libs/mobx').extendObservable;
import http from '../utils/http.js'
var action = mobx.action;

var Store = function(){
  extendObservable(this,{
    http: new http(),
    game:{},

  });

  this.getGame=key=>{

    this.http.get('/gameInfo', {
      userkey: key
    }).then(res=>{
      this.game = res.data;
    })
  }

}

export default Store;

**Comment by windy** [comment]
看官方例子:  https://github.com/80percent/wechat-weapp-mobx-todos

**Comment by laoyao789** [comment]
博主你好，下面是我看的官方的例子，稍微做了些改动，我在extendObservable里加了一个变量game,并且用setTimeOut模拟了异步数据加载，我知道在index.wxml里是可以正常监控到的，我现在想在页面的index.js里监控game的值的变动，可以做到吗？怎么做？ 官方例子里也没看到有这样的操作
todoStore.js
var mobx = require('../libs/mobx');
var extendObservable = require('../libs/mobx').extendObservable;
var computed = require('../libs/mobx').computed;
var toJS = require('../libs/mobx').toJS;
var TodoItem = require('./todoItemStore').default;
var action = mobx.action;

var TodoStore = function() {
  extendObservable(this, {
    todos: [new TodoItem('今天要早起')],
   game:{},     //新增游戏对象
    id:0,
    filters: [{ key: 'SHOW_ALL', text: '全部' }, { key: 'SHOW_ACTIVE', text: '正在进行' }, { key: 'SHOW_COMPLETED', text: '已完成' }],
    filter: 'SHOW_ALL',
    get filterTodos() {
      switch( this.filter ) {
        case 'SHOW_ALL':
          return this.todos;
        case 'SHOW_COMPLETED':
          return this.todos.filter( function(t) {
            return t.completed;
          });
        case 'SHOW_ACTIVE':
          return this.todos.filter( function(t) {
            return !t.completed;
          });
        default:
          throw new Error( 'Unknown filter: ' + filter );
      }
    },

    get totalCount() {
      return this.todos.length;
    },

    get currentCount() {
      return this.filterTodos.length;
    }
  });

//模拟异步获得游戏数据
  var _this=this;
  setTimeout(action(function(){
    var id=Math.random()*1000
    // console.log(id)
    _this.game={
      id:id,
      name:id+'name'
    }
    _this.id=id;
  }),10000)

  this.addTodo = action(function(title) {
    this.todos.push( new TodoItem(title) );
  })

  this.findByTodoId = action(function(id) {
    var item = this.todos.find( function(element) {
      return element.id === id;
    })
    return item;
  })

  this.getGameData=action(function(){
    return this.game;
  })
}

module.exports = {
  default: new TodoStore,
}

**Comment by windy** [comment]
看的不是很明白，我说一点：

使用该框架后，你在 index.js 和 index.wxml 就只使用  this.props.xxx 来引用处理就行。这些都是联动更新的。

其他你自己好好研究一下。

**Comment by laoyao789** [comment]
非常感谢，读了下源码，问题已经解决，我的意思就是想在小程序的js里实时观测到数据变化的，类似于vue的watch，目前修改了下源码，已经实现
