### ISSUE TITLE
props被注入到data上的时机太晚

### ISSUE THREAD

**Issue by Duobj** [80percent/wechat-weapp-mobx#17]
现在props是在page.onLoad时第一次被注入到page.data中，在page实例化的过程中，data.props的值一开始是undefined，onLoad时才变成state中初始化的值
下面这个场景：
state = {
  loading: true
}
在wxml中一个自定义组件绑定了props中的值：
<componentA wx:if="{{!props.loading}}"></componentA>
进入页面拉取数据后把loading变为false
期望是：loading从true=>false，进入页面后componentA先不展示，loading变成false后展示，componentA只创建一次
实际结果是：loading从undefined=>true=>false，componentA先被创建然后被销毁，又创建

目前的解决办法：
修改了observer.js
在observer方法中，先给page.data上加上props

**Comment by windy** [comment]
@Duobj 多谢反馈.

能否贴个代码看一下你的改动内容.

**Comment by Duobj** [comment]
改动贴图里了，我用的是0.1.8版本，不过看了一下0.1.9的逻辑应该也有相应的问题
![image](https://user-images.githubusercontent.com/15835797/60562825-b8ec0000-9d8b-11e9-8c78-059b7606fd7c.png)

**Comment by windy** [comment]
好主意，的确有这样的问题。

提个建议，赋值的时候建议 toJS 一下, 避免部分数据不被支持.
