### ISSUE TITLE
observer的page如果没有props的话会报错

### ISSUE THREAD

**Issue by chenzhe555** [80percent/wechat-weapp-mobx#20]
observer.js第86行，没有对mobx.observable传入参数进行校验，如果业务传入对page没有props对话会报错，目前处理都是使用这个的时候在外面做一层判断，其实这个判断可以加在observer.js文件里好点吧?
var _props = mobx.observable(page.props || {}) || {};

**Comment by windy** [comment]
嗯 我修复一下

**Comment by windy** [comment]
已在 0.2.0 版本中修复
