### ISSUE TITLE
是否有考虑支持Component呢？

### ISSUE THREAD

**Issue by bigbigbo** [80percent/wechat-weapp-mobx#21]
期望 Component 也能实现 observer 😄

**Comment by windy** [comment]
@bigbigbo 我们内部有一个支持的版本，回头发出来 :)

**Comment by bigbigbo** [comment]
@windy 谢谢

**Comment by windy** [comment]
https://github.com/dao42/wechat-weapp-mobx/pull/22 

已经支持

**Comment by bigbigbo** [comment]
@windy 感谢
