### ISSUE TITLE
关于 store 状态存储的理解问题，请教一下~

### ISSUE THREAD

**Issue by bigbigbo** [80percent/wechat-weapp-mobx#23]
你好，这几天有个疑问，像 `mobx-react` 实现全局状态是依靠 `Provider` 和 `ReactContext` 来实现全局的 `store`，也就是我在 A 页面修改了store 的状态，在 B 页面能访问到修改后的状态。

借助`wechat-weapp-mobx`也能达到 **A 页面修改了store 的状态，在 B 页面能访问到修改后的状态**。但是我发现`wechat-weapp-mobx`并没有借助小程序的`globalData`来实现，而只要`import`对应的`store`即可,是因为小程序对模块的解析是像 `webpack` 那样做的吗？对模块有缓存，从而能实现全局的 `store`吗？

**Comment by windy** [comment]
store 是单例的，而且一直有引用，所以一直存在。

**Comment by bigbigbo** [comment]
@windy 感谢回答，看到这位朋友的[实现](https://github.com/laihaibo/weapp-bmscore/blob/master/pages/index/index.js)才有了疑惑，那他这种做法是不是多此一举了呢？ 😃

**Comment by windy** [comment]
嗯 有些多余, 我看他的意图是持久化存储 store. 这个需要同步到 storage 里面. 你看一下我们 readme 里的 todolist 这个例子可能更容易懂一些.

**Comment by bigbigbo** [comment]
感谢回答 😃
