### ISSUE TITLE
mobx的computed装饰的getter 和 一般getter  无法在wxml里使用

### ISSUE THREAD

**Issue by jamieYou** [80percent/wechat-weapp-mobx#5]
```
var _mergeGetterValue = function(res, object){
  Object.getOwnPropertyNames(object).forEach( function(propertyName){
    if(propertyName === "$mobx"){ return };
    var descriptor = Object.getOwnPropertyDescriptor(object, propertyName);
    if( descriptor && !descriptor.enumerable && !descriptor.writable ){
      res[propertyName] = toJS(object[propertyName]);
    }
  })
}
```
在class里声明的getter是不可遍历的。
虽然在observer.js里有检查不可遍历的属性， 但是在class里声明的getter拦截器是声明在prototype上的, 实例化后getter是在__proto__里的, Object.getOwnPropertyNames不会去获取__proto__的属性。

目前解决方法是把computed方法里的enumerable改为true，使其可遍历。

**Comment by windy** [comment]
@jokerapi 现在这里的实现是确保支持了 computed getter 在 wxml 中可用.

你的意思是建议将 enumerable 调整为 true, 然后用 mobx 标准的 toJS 来处理?

**Comment by windy** [comment]
@jokerapi 明白了你的意思, 你们使用原型链来创建 store 了? 我的经验是不要在 store 中使用继承的对象.

**Comment by jamieYou** [comment]
我贴一下我的代码
```
class PostStore {
  @observable body = ''

  @computed get content()  {
    return this.body.replace(/src="\//g, `src=\"${apiHost}/`)
  }
}
```

const post = new PostStore()

post的content不是它的直接对象，是在__proto__才能找到content。
(这是es6的做法，即使是经过babel转换es5后，也是这样子)

Object.getOwnPropertyNames(post)不会识别__proto__的属性

而且content的enumerable是false， 用for in 是无法遍历

**Comment by windy** [comment]
@jokerapi 嗯 可能 es6 写法的 class 会转成 proto, 我再找时间处理.

**Comment by Venusjason** [comment]
请问 现在有解决吗 我也碰到了computed 在wxml里无法获取的问题

**Comment by windy** [comment]
@Venusjason ES5 的方案一直是正常的, 你也用的 ES6 写法吗?

**Comment by Venusjason** [comment]
用es5是ok的，但是我用了gulp + babel ,可以直接写es6和es7了，感觉写起来和官方文档的mobx示例差不多，代码量更少，就是computed 在wxml展示不出来
是时候考虑对es6做个支持了

**Comment by windy** [comment]
@Venusjason 嗯 好的

**Comment by Venusjason** [comment]
按照楼上的说法  目前解决方法是把computed方法里的enumerable改为true，使其可遍历。
我把 2372行 改成 `enumerable: true`, 但是没效果
不知道理解的对不对

**Comment by jamieYou** [comment]
@Venusjason 可以参考一下这里 https://github.com/jamieYou/mobx-weapp
但是需要 npm 支持。

**Comment by Venusjason** [comment]
@jamieYou 参照你之前的回答，我在这个mobx、文件 2372行  enumerable: true，computed就可以直接和视图对应了，不知道会不会引发别的问题，暂时没有发现问题

**Comment by Venusjason** [comment]
@jamieYou  说错了 改动得是 261行的createClassPropertyDecorator的第4个参数为 true

**Comment by jamieYou** [comment]
@Venusjason 我是对 computed 再封装了一遍的，没有改源码。我这边是用 npm 管理模块的。
