### ISSUE TITLE
使用小程序自定义组件后，调用时找不到action

### ISSUE THREAD

**Issue by haydenull** [80percent/wechat-weapp-mobx#6]
使用小程序自定义组件，在页面的json文件中添加
`usingComponents`
调用action会提示undefined in not a function
去掉该属性后一切正常

**Comment by windy** [comment]
我看看, 我们团队一直在用这个库, 还没遇到过类似问题.

**Comment by haydenull** [comment]
感谢，我找到问题了，这个应该是小程序的问题，这个bug只在小程序基础版本为1.6.4的时候会出现，切换到其他版本就没有问题了

**Comment by windy** [comment]
@Haaayden 好的
