### ISSUE TITLE
missing isObservableValue

### ISSUE THREAD

**Issue by CatWithWings** [80percent/wechat-weapp-mobx#7]
When I used require('./libs/observer').observer, I got some errors:

TypeError: isObservableValue is not a function

**Comment by windy** [comment]
Did you copy mobx.js to libs directory too? it should be ok right now.

**Comment by CatWithWings** [comment]
There're two js files in my libs directory, mobx.js and observer。But, it's doesn't work.

**Comment by lynx1986** [comment]
@CatWithWings 
Maybe you can include your store into page like this,
`
props: {
    category: require('../../stores/category')
}
`
that works for me.

**Comment by windy** [comment]
@CatWithWings fixed, not sure why. see:  https://github.com/80percent/wechat-weapp-mobx/blob/master/dist/observer.js#L10
