### ISSUE TITLE
如何在小程序组件中使用 Mobx

### ISSUE THREAD

**Issue by WuYunlong** [80percent/wechat-weapp-mobx#9]
现在在页面上使用 可以进行全局的状态管理并且可以实时更新
但是现在需求是在页面上有一个自定义组件  player 这个组件如何使用全局数据进行更新 
只能在页面上进行传递吗 
``` javascript
<player player-info="{{props.player.info}}"></player>
```
能否直接在我的组件里面使用 望指教

**Comment by windy** [comment]
组件的话就不建议使用全局状态了, 你可以试一下在 props 里定义看看可行不, 但不建议这么搞. 组件肯定只有输入输出要确定的.
